services:
  rust-actix-web:
    build:
      context: rust-actix-web
      dockerfile: rust.Dockerfile
    environment:
      - RUST_LOG=debug
    ports:
      - 8080:8080
    command: /app/target/release/rust-webserver
  python-fastapi:
    build:
      context: python-webserver
      dockerfile: python.Dockerfile
    ports:
      - 8081:8081
    command: fastapi run --port=8081 --workers=1
  rust-rwf:
    build:
      context: rust-rwf
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=debug
    ports:
      - 8082:8082
    command: /app/target/release/rust-rwf
  python-robyn:
    build:
      context: python-robyn
      dockerfile: Dockerfile
    environment:
      - ROBYN_HOST=0.0.0.0
      - ROBYN_PORT=8083
    ports:
      - 8083:8083
    command: python -m robyn main.py